import { describe, it, expect } from 'vitest'
import { jsonToCSharp } from './json-to-csharp.js'

describe('jsonToCSharp', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToCSharp('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToCSharp('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates C# class from a flat object', async () => {
    const r = await jsonToCSharp(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated|struct AutoGenerated/)
  })

  it('generates a separate type for nested objects', async () => {
    const r = await jsonToCSharp(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    const matches = r.code.match(/class \w+|struct \w+/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  it('uses default namespace "QuickType" when not specified', async () => {
    const r = await jsonToCSharp('{"a": 1}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/namespace QuickType/)
  })

  it('uses custom namespace when provided', async () => {
    const r = await jsonToCSharp('{"a": 1}', { namespace: 'MyApp' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/namespace MyApp/)
    expect(r.code).not.toMatch(/namespace QuickType/)
  })

  it('uses T[] by default for arrays (C# quicktype default is array)', async () => {
    const r = await jsonToCSharp('{"tags": ["a", "b"]}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/\[\]/)
    expect(r.code).not.toMatch(/List</)
  })

  it('uses T[] when useList: false', async () => {
    const r = await jsonToCSharp('{"tags": ["a", "b"]}', { useList: false })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/\[\]/)
    expect(r.code).not.toMatch(/List</)
  })

  it('uses List<T> when useList: true', async () => {
    const r = await jsonToCSharp('{"tags": ["a", "b"]}', { useList: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/List</)
  })

  it('handles top-level array input', async () => {
    const r = await jsonToCSharp('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToCSharp('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToCSharp('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToCSharp('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class User|struct User/)
    expect(r.code).not.toMatch(/class AutoGenerated|struct AutoGenerated/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToCSharp('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated|struct AutoGenerated/)
    expect(r.warning).toMatch(/合法 C# 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToCSharp('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty', async () => {
    const r = await jsonToCSharp('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })
})
