import { describe, it, expect } from 'vitest'
import { jsonToPython } from './json-to-python.js'

describe('jsonToPython', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToPython('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToPython('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates Python class from a flat object', async () => {
    const r = await jsonToPython(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated/)
  })

  it('generates a separate class for nested objects', async () => {
    const r = await jsonToPython(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    const matches = r.code.match(/class \w+/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  it('emits Optional fields when allOptional: true', async () => {
    const r = await jsonToPython('{"a": 1}', { allOptional: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/Optional\[/)
  })

  it('does NOT emit Optional when allOptional: false', async () => {
    const r = await jsonToPython('{"a": 1}', { allOptional: false })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).not.toMatch(/Optional\[/)
  })

  it('emits pydantic BaseModel when pydantic: true', async () => {
    const r = await jsonToPython('{"a": 1}', { pydantic: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/BaseModel/)
  })

  it('handles top-level array input', async () => {
    const r = await jsonToPython('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToPython('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToPython('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToPython('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class User/)
    expect(r.code).not.toMatch(/class AutoGenerated/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToPython('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated/)
    expect(r.warning).toMatch(/合法 Python 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToPython('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty (uses default)', async () => {
    const r = await jsonToPython('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })
})
