<template>
  <div class="json-to-php-page">
    <h1 class="text-3xl font-bold mb-6">
      JSON → PHP 转换
    </h1>

    <!-- Toolbar -->
    <div class="flex flex-wrap items-center gap-4 mb-4">
      <div class="form-control">
        <label class="label py-1"><span class="label-text">顶层类名</span></label>
        <input
          v-model="typeName"
          type="text"
          class="input input-bordered input-sm w-48 font-mono"
          placeholder="AutoGenerated"
          @input="scheduleGenerate"
        >
      </div>
      <label class="label cursor-pointer gap-2">
        <input
          v-model="withSet"
          type="checkbox"
          class="checkbox checkbox-sm"
          @change="regenerate"
        >
        <span class="label-text">生成 setter</span>
      </label>
      <label class="label cursor-pointer gap-2">
        <input
          v-model="withClosing"
          type="checkbox"
          class="checkbox checkbox-sm"
          @change="regenerate"
        >
        <span class="label-text">输出 &lt;?&gt; 闭合标签</span>
      </label>
    </div>

    <div class="flex gap-4">
      <!-- Input -->
      <div class="flex-1 form-control min-w-0">
        <label class="label mb-2">
          <span class="label-text font-semibold">JSON 输入</span>
          <button
            v-if="input"
            class="btn btn-ghost btn-xs gap-1"
            @click="copyText(input, 'inputCopied')"
          >
            <Icon
              v-if="inputCopied"
              icon="lucide:check"
              class="w-3.5 h-3.5 text-success"
            />
            <Icon
              v-else
              icon="lucide:clipboard"
              class="w-3.5 h-3.5"
            />
            {{ inputCopied ? '已复制！' : '复制' }}
          </button>
        </label>
        <div
          ref="inputEditorEl"
          class="cm-container border border-base-300"
        />
      </div>

      <!-- Output -->
      <div class="flex-1 form-control min-w-0">
        <label class="label mb-2">
          <span class="label-text font-semibold">PHP 输出</span>
          <button
            v-if="output"
            class="btn btn-ghost btn-xs gap-1"
            @click="copyText(output, 'outputCopied')"
          >
            <Icon
              v-if="outputCopied"
              icon="lucide:check"
              class="w-3.5 h-3.5 text-success"
            />
            <Icon
              v-else
              icon="lucide:clipboard"
              class="w-3.5 h-3.5"
            />
            {{ outputCopied ? '已复制！' : '复制' }}
          </button>
        </label>
        <div
          ref="outputEditorEl"
          class="cm-container border border-base-300"
        />
      </div>
    </div>

    <div class="flex items-center justify-between mt-4 gap-4">
      <p
        v-if="error"
        class="text-error text-sm flex-1 min-w-0 truncate"
      >
        {{ error }}
      </p>
      <p
        v-else-if="warning"
        class="text-warning text-sm flex-1 min-w-0 truncate"
      >
        {{ warning }}
      </p>
      <span
        v-else
        class="flex-1"
      />
      <button
        class="btn btn-ghost btn-sm gap-1"
        @click="clear"
      >
        <Icon
          icon="lucide:trash-2"
          class="w-4 h-4"
        />
        清空
      </button>
    </div>
  </div>
</template>

<script setup>
import { Icon } from '@iconify/vue'
import { ref, onMounted, onBeforeUnmount, watch, nextTick } from 'vue'
import { EditorView, keymap, lineNumbers, highlightActiveLineGutter, highlightActiveLine, drawSelection, rectangularSelection, highlightSpecialChars } from '@codemirror/view'
import { EditorState } from '@codemirror/state'
import { json as jsonLang } from '@codemirror/lang-json'
import { php as phpLang } from '@codemirror/lang-php'
import { oneDark } from '@codemirror/theme-one-dark'
import { defaultKeymap, history, historyKeymap, indentWithTab } from '@codemirror/commands'
import { syntaxHighlighting, defaultHighlightStyle, bracketMatching } from '@codemirror/language'
import { closeBrackets, closeBracketsKeymap } from '@codemirror/autocomplete'
import { searchKeymap, highlightSelectionMatches } from '@codemirror/search'
import { jsonToPhp } from './json-to-php.js'
import { useTheme } from '../../composables/useTheme.js'

const DEFAULT_INPUT = JSON.stringify({
  name: 'wxsm',
  age: 18,
  active: true,
  tags: ['dev', 'php'],
  address: { city: 'BJ', zip: '100000' },
}, null, 2)

const input = ref(DEFAULT_INPUT)
const output = ref('')
const error = ref('')
const warning = ref('')
const withSet = ref(false)
const withClosing = ref(false)
const typeName = ref('')
const inputCopied = ref(false)
const outputCopied = ref(false)

const inputEditorEl = ref(null)
const outputEditorEl = ref(null)
let inputEditor = null
let outputEditor = null
let debounceTimer = null

const { theme } = useTheme()

function getThemeExt() {
  return theme.value === 'dark' ? oneDark : []
}

function createExtensions(langExt, onChange) {
  return [
    lineNumbers(),
    highlightActiveLineGutter(),
    highlightSpecialChars(),
    history(),
    drawSelection(),
    EditorState.allowMultipleSelections.of(true),
    syntaxHighlighting(defaultHighlightStyle, { fallback: true }),
    bracketMatching(),
    closeBrackets(),
    rectangularSelection(),
    highlightActiveLine(),
    highlightSelectionMatches(),
    keymap.of([
      ...closeBracketsKeymap,
      ...defaultKeymap,
      ...searchKeymap,
      ...historyKeymap,
      indentWithTab,
    ]),
    langExt,
    EditorView.updateListener.of(onChange),
    EditorView.theme({
      '&': { height: '100%' },
      '.cm-scroller': { overflow: 'auto' },
    }),
  ]
}

function inputOnChange(update) {
  if (!update.docChanged) return
  input.value = update.state.doc.toString()
  scheduleGenerate()
}

function outputOnChange() {
  // 输出是只读的，不处理变更
}

function createEditors() {
  if (inputEditorEl.value && !inputEditor) {
    inputEditor = new EditorView({
      state: EditorState.create({
        doc: input.value,
        extensions: [...createExtensions(jsonLang(), inputOnChange), getThemeExt()],
      }),
      parent: inputEditorEl.value,
    })
  }
  if (outputEditorEl.value && !outputEditor) {
    outputEditor = new EditorView({
      state: EditorState.create({
        doc: output.value,
        extensions: [
          ...createExtensions(phpLang(), outputOnChange),
          EditorState.readOnly.of(true),
          getThemeExt(),
        ],
      }),
      parent: outputEditorEl.value,
    })
  }
}

function destroyEditors() {
  inputEditor?.destroy()
  inputEditor = null
  outputEditor?.destroy()
  outputEditor = null
}

async function generate() {
  const r = await jsonToPhp(input.value, {
    withSet: withSet.value,
    withClosing: withClosing.value,
    typeName: typeName.value.trim() || 'AutoGenerated',
  })
  if (r.ok) {
    error.value = ''
    warning.value = r.warning || ''
    output.value = r.code
    syncOutputEditor()
  } else {
    // 校验失败时保留上一次成功的 PHP 输出,只更新错误信息
    warning.value = ''
    error.value = r.error
  }
}

function syncOutputEditor() {
  if (!outputEditor) return
  outputEditor.dispatch({
    changes: { from: 0, to: outputEditor.state.doc.length, insert: output.value },
  })
}

function scheduleGenerate() {
  error.value = ''
  warning.value = ''
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(generate, 300)
}

function regenerate() {
  if (debounceTimer) {
    clearTimeout(debounceTimer)
    debounceTimer = null
  }
  generate()
}

function clear() {
  input.value = ''
  output.value = ''
  error.value = ''
  warning.value = ''
  if (inputEditor) {
    inputEditor.dispatch({
      changes: { from: 0, to: inputEditor.state.doc.length, insert: '' },
    })
  }
  syncOutputEditor()
}

async function copyText(text, flag) {
  try {
    await navigator.clipboard.writeText(text)
    if (flag === 'inputCopied') {
      inputCopied.value = true
      setTimeout(() => { inputCopied.value = false }, 1500)
    } else {
      outputCopied.value = true
      setTimeout(() => { outputCopied.value = false }, 1500)
    }
  } catch { /* clipboard not available */ }
}

watch(theme, async () => {
  destroyEditors()
  await nextTick()
  createEditors()
  syncOutputEditor()
})

onMounted(() => {
  createEditors()
  generate()
})

onBeforeUnmount(() => {
  if (debounceTimer) clearTimeout(debounceTimer)
  destroyEditors()
})
</script>

<style>
.json-to-php-page .cm-container {
  height: calc(100vh - 260px);
  min-height: 400px;
  border-radius: var(--radius-field, 0.5rem);
  overflow: hidden;
}

.json-to-php-page .cm-container .cm-editor {
  height: 100%;
  font-size: 0.875rem;
}

.json-to-php-page .cm-container .cm-editor.cm-focused {
  outline: none;
}

:not([data-theme="dark"]) .json-to-php-page .cm-container .cm-editor {
  background: var(--color-base-300);
}
:not([data-theme="dark"]) .json-to-php-page .cm-container .cm-editor .cm-gutters {
  background: var(--color-base-300);
  border-right: 1px solid var(--color-base-100);
}
:not([data-theme="dark"]) .json-to-php-page .cm-container .cm-editor .cm-activeLineGutter {
  background: var(--color-base-200);
}
:not([data-theme="dark"]) .json-to-php-page .cm-container .cm-editor .cm-activeLine {
  background: var(--color-base-200);
}
</style>
