import { quicktype, jsonInputForTargetLanguage, InputData } from 'quicktype-core'

/**
 * @param {string} jsonString
 * @param {{ withSet?: boolean, withClosing?: boolean, typeName?: string }} [options]
 * @returns {Promise<{ ok: true, code: string, warning?: string } | { ok: false, error: string }>}
 *
 * quicktype-core PHP renderer 行为（对照
 * node_modules/quicktype-core/dist/language/Php/language.js、PhpRenderer.js）：
 * - PHP 没有 `just-types` 选项,渲染器始终输出完整 class：含属性、构造函数、getter。
 *   with-get 默认 true,fast-get 默认 false（getter 带类型校验）,这里保留默认。
 * - `with-set` 默认 false → 是否额外生成 setter。
 * - `with-closing` 默认 false → 是否输出 `?>` 结束标签（PSR-12 风格不推荐加）。
 * - `acronym-style` 默认 Pascal。
 *
 * `typeName` 作为 `addSource({ name })` 传入,控制顶层 PHP 类名。非合法 PHP 标识符时
 * 回退到 'AutoGenerated' 并返回 warning,让 UI 提示用户。
 */
const PHP_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/

export async function jsonToPhp(jsonString, {
  withSet = false,
  withClosing = false,
  typeName = 'AutoGenerated',
} = {}) {
  if (!jsonString || jsonString.trim() === '') {
    return { ok: true, code: '' }
  }

  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch (e) {
    return { ok: false, error: 'JSON 解析失败：' + e.message }
  }

  const trimmedName = (typeName || '').trim()
  const isValidName = trimmedName === '' || PHP_IDENT_RE.test(trimmedName)
  const safeName = isValidName ? (trimmedName || 'AutoGenerated') : 'AutoGenerated'
  const warning = isValidName
    ? undefined
    : `类名 "${trimmedName}" 不是合法 PHP 标识符`

  try {
    const jsonInput = jsonInputForTargetLanguage('php')
    await jsonInput.addSource({ name: safeName, samples: [JSON.stringify(parsed)] })
    const inputData = new InputData()
    inputData.addInput(jsonInput)

    const rendererOptions = {
      'with-set': withSet,
      'with-closing': withClosing,
    }

    const result = await quicktype({
      lang: 'php',
      inputData,
      rendererOptions,
    })
    return { ok: true, code: result.lines.join('\n'), warning }
  } catch (e) {
    return { ok: false, error: '生成失败：' + e.message }
  }
}
