import { describe, it, expect } from 'vitest'
import { jsonToJava } from './json-to-java.js'

describe('jsonToJava', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToJava('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToJava('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates Java class from a flat object', async () => {
    const r = await jsonToJava(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated/)
  })

  it('generates a separate class for nested objects', async () => {
    const r = await jsonToJava(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    const matches = r.code.match(/class \w+/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  it('uses List<T> by default for arrays', async () => {
    const r = await jsonToJava('{"tags": ["a", "b"]}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/List</)
  })

  it('uses T[] when useList: false', async () => {
    const r = await jsonToJava('{"tags": ["a", "b"]}', { useList: false })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).not.toMatch(/List</)
  })

  it('emits lombok annotations when lombok: true', async () => {
    const r = await jsonToJava('{"a": 1}', { lombok: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/@Data|@Getter|lombok/)
  })

  it('does NOT emit lombok when lombok: false (default)', async () => {
    const r = await jsonToJava('{"a": 1}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).not.toMatch(/lombok/)
  })

  it('handles top-level array input', async () => {
    const r = await jsonToJava('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToJava('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToJava('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToJava('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class User/)
    expect(r.code).not.toMatch(/class AutoGenerated/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToJava('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated/)
    expect(r.warning).toMatch(/合法 Java 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToJava('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty', async () => {
    const r = await jsonToJava('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })
})
