import { quicktype, jsonInputForTargetLanguage, InputData } from 'quicktype-core'

/**
 * @param {string} jsonString
 * @param {{ useList?: boolean, lombok?: boolean, typeName?: string }} [options]
 * @returns {Promise<{ ok: true, code: string, warning?: string } | { ok: false, error: string }>}
 *
 * quicktype-core Java renderer 行为：
 * - `just-types: true`  只输出 POJO class，不输出 Jackson 注解与反序列化代码
 * - `array-type`  enum：`'list'` → `List<T>`，`'array'` → `T[]`。默认 `'list'`。
 * - `lombok: true`  使用 Lombok 注解（@Data 等）替代手写 getter/setter
 *
 * `typeName` 作为 `addSource({ name })` 传入，控制顶层类名。非合法 Java 标识符时
 * 回退到 'AutoGenerated' 并返回 warning，让 UI 提示用户。
 */
const JAVA_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/

export async function jsonToJava(jsonString, {
  useList = true,
  lombok = false,
  typeName = 'AutoGenerated',
} = {}) {
  if (!jsonString || jsonString.trim() === '') {
    return { ok: true, code: '' }
  }

  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch (e) {
    return { ok: false, error: 'JSON 解析失败：' + e.message }
  }

  const trimmedName = (typeName || '').trim()
  const isValidName = trimmedName === '' || JAVA_IDENT_RE.test(trimmedName)
  const safeName = isValidName ? (trimmedName || 'AutoGenerated') : 'AutoGenerated'
  const warning = isValidName
    ? undefined
    : `结构体名 "${trimmedName}" 不是合法 Java 标识符`

  try {
    const jsonInput = jsonInputForTargetLanguage('java')
    await jsonInput.addSource({ name: safeName, samples: [JSON.stringify(parsed)] })
    const inputData = new InputData()
    inputData.addInput(jsonInput)

    const rendererOptions = {
      'just-types': true,
      'array-type': useList ? 'list' : 'array',
    }
    if (lombok) rendererOptions['lombok'] = true

    const result = await quicktype({
      lang: 'java',
      inputData,
      rendererOptions,
    })
    return { ok: true, code: result.lines.join('\n'), warning }
  } catch (e) {
    return { ok: false, error: '生成失败：' + e.message }
  }
}
