import { describe, it, expect } from 'vitest'
import { jsonToTs } from './json-to-ts.js'

describe('jsonToTs', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToTs('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns empty code for whitespace-only input', async () => {
    const r = await jsonToTs('   \n\t  ')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToTs('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates TypeScript interface from a flat object', async () => {
    const r = await jsonToTs(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/interface AutoGenerated/)
    expect(r.code).toMatch(/\bstring\b/)
    expect(r.code).toMatch(/\bnumber\b/)
    expect(r.code).toMatch(/\bboolean\b/)
  })

  it('generates a separate interface for nested objects', async () => {
    const r = await jsonToTs(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    const matches = r.code.match(/interface \w+/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  it('emits optional fields when allOptional: true', async () => {
    const r = await jsonToTs(JSON.stringify({ name: 'foo', age: 18 }), { allOptional: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    // 至少有一个字段渲染为 `field?: type`
    expect(r.code).toMatch(/\?\s*:/)
  })

  it('does NOT emit optional fields when allOptional: false (default)', async () => {
    const r = await jsonToTs(JSON.stringify({ name: 'foo', age: 18 }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).not.toMatch(/\?\s*:/)
  })

  it('handles top-level array input', async () => {
    const r = await jsonToTs('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToTs('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToTs('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToTs('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/interface User\b/)
    expect(r.code).not.toMatch(/interface AutoGenerated/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToTs('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/interface AutoGenerated/)
    expect(r.warning).toMatch(/合法 TypeScript 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToTs('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty (uses default)', async () => {
    const r = await jsonToTs('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('outputs `type Foo = {...}` when preferTypes: true', async () => {
    const r = await jsonToTs('{"a": 1}', { preferTypes: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/type AutoGenerated\s*=/)
    expect(r.code).not.toMatch(/interface AutoGenerated/)
  })

  it('outputs `interface Foo` when preferTypes: false (default)', async () => {
    const r = await jsonToTs('{"a": 1}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/interface AutoGenerated/)
    expect(r.code).not.toMatch(/type AutoGenerated\s*=/)
  })
})
