import { quicktype, jsonInputForTargetLanguage, InputData } from 'quicktype-core'

/**
 * @param {string} jsonString
 * @param {{ allOptional?: boolean, preferTypes?: boolean, typeName?: string }} [options]
 * @returns {Promise<{ ok: true, code: string, warning?: string } | { ok: false, error: string }>}
 *
 * quicktype-core TypeScript renderer 行为：
 * - `just-types: true`  只输出类型声明，不输出 runtime 解析代码
 * - `prefer-types: true` 输出 `type Foo = { ... }`；否则输出 `interface Foo { ... }`
 * - 顶层 option `allPropertiesOptional: true` 让所有字段渲染为 `field?: T`
 *
 * `typeName` 作为 `addSource({ name })` 传入，控制顶层类型名。非合法 TS 标识符时
 * 回退到 'AutoGenerated' 并返回 warning，让 UI 提示用户。
 */
const TS_IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/

export async function jsonToTs(jsonString, {
  allOptional = false,
  preferTypes = false,
  typeName = 'AutoGenerated',
} = {}) {
  if (!jsonString || jsonString.trim() === '') {
    return { ok: true, code: '' }
  }

  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch (e) {
    return { ok: false, error: 'JSON 解析失败：' + e.message }
  }

  const trimmedName = (typeName || '').trim()
  const isValidName = trimmedName === '' || TS_IDENT_RE.test(trimmedName)
  const safeName = isValidName ? (trimmedName || 'AutoGenerated') : 'AutoGenerated'
  const warning = isValidName
    ? undefined
    : `结构体名 "${trimmedName}" 不是合法 TypeScript 标识符`

  try {
    const jsonInput = jsonInputForTargetLanguage('typescript')
    await jsonInput.addSource({ name: safeName, samples: [JSON.stringify(parsed)] })
    const inputData = new InputData()
    inputData.addInput(jsonInput)

    const rendererOptions = { 'just-types': true }
    if (preferTypes) rendererOptions['prefer-types'] = true
    const extraOptions = {}
    if (allOptional) extraOptions.allPropertiesOptional = true

    const result = await quicktype({
      lang: 'typescript',
      inputData,
      rendererOptions,
      ...extraOptions,
    })
    return { ok: true, code: result.lines.join('\n'), warning }
  } catch (e) {
    return { ok: false, error: '生成失败：' + e.message }
  }
}
