import { quicktype, jsonInputForTargetLanguage, InputData } from 'quicktype-core'

/**
 * @param {string} jsonString
 * @param {{ omitempty?: boolean, typeName?: string }} [options]
 * @returns {Promise<{ ok: true, code: string, warning?: string } | { ok: false, error: string }>}
 *
 * quicktype-core 的实际入参形态（Task 2 实测）：
 * - `quicktype()` 不接受字符串形式的 `inputData`，也不接受 `source`/`targetLanguage`。
 * - 必须构造 `InputData` 实例 + `jsonInputForTargetLanguage('go')` 喂样本。
 * - Go renderer 的 option 名为 `just-types` 和 `omit-empty`（不是 `just-types-and-omitempty`）。
 * - 单样本下所有字段都是 required，`omit-empty` 单独使用不会产生 `omitempty` tag。
 *   为了让 `omitempty` 开关对单样本也有可见效果：
 *   - `omitempty: true`  → 叠加 `allPropertiesOptional: true`，所有字段变 optional 指针/切片，
 *     配合 `omit-empty: true` 生成 `*T` / `[]T` + `,omitempty`。
 *   - `omitempty: false` → 仅 `just-types`，字段为值类型，不带 `,omitempty`。
 * - `typeName` 作为 `addSource({ name })` 传入，控制顶层 Go 类型名。非合法 Go 标识符时
 *   回退到 'AutoGenerated' 并返回 warning，让 UI 提示用户。
 */
const GO_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/

export async function jsonToGo(jsonString, { omitempty = false, typeName = 'AutoGenerated' } = {}) {
  if (!jsonString || jsonString.trim() === '') {
    return { ok: true, code: '' }
  }

  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch (e) {
    return { ok: false, error: 'JSON 解析失败：' + e.message }
  }

  const trimmedName = (typeName || '').trim()
  const isValidName = trimmedName === '' || GO_IDENT_RE.test(trimmedName)
  const safeName = isValidName ? (trimmedName || 'AutoGenerated') : 'AutoGenerated'
  const warning = isValidName
    ? undefined
    : `结构体名 "${trimmedName}" 不是合法 Go 标识符`

  try {
    const jsonInput = jsonInputForTargetLanguage('go')
    await jsonInput.addSource({ name: safeName, samples: [JSON.stringify(parsed)] })
    const inputData = new InputData()
    inputData.addInput(jsonInput)

    const rendererOptions = { 'just-types': true }
    const extraOptions = {}
    if (omitempty) {
      rendererOptions['omit-empty'] = true
      extraOptions.allPropertiesOptional = true
    }

    const result = await quicktype({
      lang: 'go',
      inputData,
      rendererOptions,
      ...extraOptions,
    })
    return { ok: true, code: result.lines.join('\n'), warning }
  } catch (e) {
    return { ok: false, error: '生成失败：' + e.message }
  }
}
