import { describe, it, expect } from 'vitest'
import { jsonToGo } from './json-to-go.js'

describe('jsonToGo', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToGo('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToGo('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates Go struct from a flat object', async () => {
    const r = await jsonToGo(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/type AutoGenerated struct/)
    expect(r.code).toMatch(/\bstring\b/)
    expect(r.code).toMatch(/int64/)
    expect(r.code).toMatch(/\bbool\b/)
  })

  it('generates a separate struct for nested objects', async () => {
    const r = await jsonToGo(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    // 两个 type ... struct 声明
    const matches = r.code.match(/type \w+ struct/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  it('emits omitempty when omitempty: true (default)', async () => {
    const r = await jsonToGo(JSON.stringify({ name: 'foo' }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toContain('omitempty')
  })

  it('does NOT emit omitempty when omitempty: false', async () => {
    const r = await jsonToGo(JSON.stringify({ name: 'foo' }), { omitempty: false })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).not.toContain('omitempty')
  })

  // 锁定 allPropertiesOptional 副作用：omitempty=true 时字段渲染为指针类型
  it('renders pointer types when omitempty: true', async () => {
    const r = await jsonToGo('{"a": 1}', { omitempty: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/\*\w+/) // *int64 之类
  })

  it('handles top-level array input', async () => {
    const r = await jsonToGo('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToGo('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToGo('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToGo('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/type User struct/)
    expect(r.code).not.toMatch(/type AutoGenerated struct/)
  })

  it('accepts lowercase-leading typeName (quicktitle capitalizes it)', async () => {
    const r = await jsonToGo('{"a": 1}', { typeName: 'userConfig' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    // quicktype capitalizes the first letter to follow Go export convention
    expect(r.code).toMatch(/type UserConfig struct/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToGo('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/type AutoGenerated struct/)
    expect(r.warning).toMatch(/合法 Go 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToGo('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty (uses default)', async () => {
    const r = await jsonToGo('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })
})
