import { quicktype, jsonInputForTargetLanguage, InputData } from 'quicktype-core'

/**
 * @param {string} jsonString
 * @param {{ namespace?: string, typeName?: string }} [options]
 * @returns {Promise<{ ok: true, code: string, warning?: string } | { ok: false, error: string }>}
 *
 * quicktype-core C++ renderer 行为（Task 8 实测，对照
 * node_modules/quicktype-core/dist/language/CPlusPlus/language.js 与
 * CPlusPlusRenderer.js）：
 * - `just-types: true`  只输出类型声明，不输出 nlohmann json 反序列化代码与注释。
 *   实测 C++ renderer 输出的是 `class`（不是 `struct`），且 just-types 分支会跳过
 *   `emitNamespaces`（见 CPlusPlusRenderer.js emitSource: justTypes 分支直接调
 *   `emitTypes()`），所以 `namespace` option 在 just-types 模式下不生效。为了拿到
 *   干净的类型声明，这里保留 just-types=true，namespace option 仍接收但只在
 *   UI/未来切换到 full 模式时才有意义。
 * - `namespace`  StringOption，默认 'quicktype'，仅在非 just-types 模式下生效。
 *
 * `typeName` 作为 `addSource({ name })` 传入，控制顶层 class 名。非合法 C++ 标识符时
 * 回退到 'AutoGenerated' 并返回 warning，让 UI 提示用户。
 */
const CPP_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/

export async function jsonToCpp(jsonString, {
  namespace = 'quicktype',
  typeName = 'AutoGenerated',
} = {}) {
  if (!jsonString || jsonString.trim() === '') {
    return { ok: true, code: '' }
  }

  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch (e) {
    return { ok: false, error: 'JSON 解析失败：' + e.message }
  }

  const trimmedName = (typeName || '').trim()
  const isValidName = trimmedName === '' || CPP_IDENT_RE.test(trimmedName)
  const safeName = isValidName ? (trimmedName || 'AutoGenerated') : 'AutoGenerated'
  const warning = isValidName
    ? undefined
    : `结构体名 "${trimmedName}" 不是合法 C++ 标识符`

  try {
    const jsonInput = jsonInputForTargetLanguage('cpp')
    await jsonInput.addSource({ name: safeName, samples: [JSON.stringify(parsed)] })
    const inputData = new InputData()
    inputData.addInput(jsonInput)

    const rendererOptions = {
      'just-types': true,
      namespace,
    }

    const result = await quicktype({
      lang: 'cpp',
      inputData,
      rendererOptions,
    })
    return { ok: true, code: result.lines.join('\n'), warning }
  } catch (e) {
    return { ok: false, error: '生成失败：' + e.message }
  }
}
