import { describe, it, expect } from 'vitest'
import { jsonToCpp } from './json-to-cpp.js'

describe('jsonToCpp', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToCpp('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToCpp('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates C++ class from a flat object', async () => {
    const r = await jsonToCpp(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated/)
  })

  it('generates a separate class for nested objects', async () => {
    const r = await jsonToCpp(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    const matches = r.code.match(/class \w+/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  // quicktype C++ renderer with `just-types: true` suppresses the `namespace`
  // wrapper (see CPlusPlusRenderer.js emitSource: justTypes branch emits types
  // directly without emitNamespaces). jsonToCpp post-processes the output:
  // when namespace is not the default 'quicktype', it wraps the code in
  // `namespace X { ... }`. These two tests assert that behavior.
  it('does not wrap in namespace when using default', async () => {
    const r = await jsonToCpp('{"a": 1}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).not.toMatch(/namespace quicktype/)
  })

  it('uses custom namespace when provided', async () => {
    const r = await jsonToCpp('{"a": 1}', { namespace: 'myapp' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/namespace myapp/)
    expect(r.code).toMatch(/namespace myapp {/)
  })

  it('handles top-level array input', async () => {
    const r = await jsonToCpp('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToCpp('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToCpp('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToCpp('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class User/)
    expect(r.code).not.toMatch(/class AutoGenerated/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToCpp('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/class AutoGenerated/)
    expect(r.warning).toMatch(/合法 C\+\+ 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToCpp('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty', async () => {
    const r = await jsonToCpp('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })
})
