import { describe, it, expect } from 'vitest'
import { jsonToRust } from './json-to-rust.js'

describe('jsonToRust', () => {
  it('returns empty code for empty input', async () => {
    const r = await jsonToRust('')
    expect(r.ok).toBe(true)
    if (r.ok) expect(r.code).toBe('')
  })

  it('returns a clean error for invalid JSON', async () => {
    const r = await jsonToRust('{ not json')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.error).toMatch(/JSON/)
  })

  it('generates Rust struct from a flat object', async () => {
    const r = await jsonToRust(JSON.stringify({ name: 'foo', age: 18, active: true }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/struct AutoGenerated/)
  })

  it('generates a separate struct for nested objects', async () => {
    const r = await jsonToRust(JSON.stringify({ outer: { inner: 1 } }))
    expect(r.ok).toBe(true)
    if (!r.ok) return
    const matches = r.code.match(/struct \w+/g) || []
    expect(matches.length).toBeGreaterThanOrEqual(2)
  })

  it('derives Debug by default', async () => {
    const r = await jsonToRust('{"a": 1}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/Debug/)
  })

  it('derives Clone by default', async () => {
    const r = await jsonToRust('{"a": 1}')
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/Clone/)
  })

  it('disables Debug derive when deriveDebug: false', async () => {
    const r = await jsonToRust('{"a": 1}', { deriveDebug: false })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    // derive 行不应包含 Debug（但其它地方可能有 Debug 字样，故检查 derive 行）
    expect(r.code).not.toMatch(/^#\[derive.*Debug.*\]/m)
  })

  it('emits skip_serializing_if when skipNone: true', async () => {
    const r = await jsonToRust('{"a": 1}', { skipNone: true })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    // Rust renderer 对 Option<T> 字段加 `#[serde(skip_serializing_if = "Option::is_none")]`，
    // 不是类级 `skip_serializing_none`；单样本下需 allPropertiesOptional 才会有 Option 字段。
    expect(r.code).toMatch(/skip_serializing_if/)
  })

  it('handles top-level array input', async () => {
    const r = await jsonToRust('[1, 2, 3]')
    expect(r.ok).toBe(true)
  })

  it('handles null field value', async () => {
    const r = await jsonToRust('{"a": null}')
    expect(r.ok).toBe(true)
  })

  it('handles mixed-type array', async () => {
    const r = await jsonToRust('[1, "a", true]')
    expect(r.ok).toBe(true)
  })

  it('uses custom typeName when provided', async () => {
    const r = await jsonToRust('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/struct User/)
    expect(r.code).not.toMatch(/struct AutoGenerated/)
  })

  it('falls back to AutoGenerated and returns warning when typeName is invalid', async () => {
    const r = await jsonToRust('{"a": 1}', { typeName: '1bad name!' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.code).toMatch(/struct AutoGenerated/)
    expect(r.warning).toMatch(/合法 Rust 标识符/)
  })

  it('returns no warning when typeName is valid', async () => {
    const r = await jsonToRust('{"a": 1}', { typeName: 'User' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })

  it('returns no warning when typeName is empty', async () => {
    const r = await jsonToRust('{"a": 1}', { typeName: '' })
    expect(r.ok).toBe(true)
    if (!r.ok) return
    expect(r.warning).toBeUndefined()
  })
})
