import { quicktype, jsonInputForTargetLanguage, InputData } from 'quicktype-core'

/**
 * @param {string} jsonString
 * @param {{ deriveDebug?: boolean, deriveClone?: boolean, skipNone?: boolean, typeName?: string }} [options]
 * @returns {Promise<{ ok: true, code: string, warning?: string } | { ok: false, error: string }>}
 *
 * quicktype-core Rust renderer 实际行为（Task 4 实测，对照
 * node_modules/quicktype-core/dist/language/Rust/RustRenderer.js + language.js）：
 * - Rust 渲染器没有 `just-types` option（与 Go/Python 不同）。默认会在头部输出
 *   `// Example code that deserializes ...` 注释，要用 `leading-comments: false` 关掉。
 * - `derive-debug` / `derive-clone` / `derive-partial-eq` 都是 BooleanOption，默认分别为
 *   true / true / false。derive 行形如
 *   `#[derive(Debug, Clone, Serialize, Deserialize)]`，其中 `Serialize, Deserialize` 由
 *   renderer 硬编码追加，不受 option 控制。传 `false` 即从 derive 行移除对应 trait。
 * - `skip-serializing-none: true` 只对 nullable union 字段（渲染为 `Option<T>`）逐个加
 *   `#[serde(skip_serializing_if = "Option::is_none")]`（注意是 `skip_serializing_if`，
 *   不是 `skip_serializing_none`；且仅对 UnionType 触发，`null` 单值会被推断为
 *   `Option<serde_json::Value>` 不触发）。单样本下字段都是 required，为了让 `skipNone`
 *   开关对单样本也有可见效果，开启时同时叠加 `allPropertiesOptional: true`，所有字段
 *   变 `Option<T>`，renderer 即为每个字段加 `skip_serializing_if` 属性。
 *
 * `typeName` 作为 `addSource({ name })` 传入，控制顶层 struct 名。非合法 Rust 标识符时
 * 回退到 'AutoGenerated' 并返回 warning，让 UI 提示用户。
 */
const RS_IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/

export async function jsonToRust(jsonString, {
  deriveDebug = true,
  deriveClone = true,
  skipNone = false,
  typeName = 'AutoGenerated',
} = {}) {
  if (!jsonString || jsonString.trim() === '') {
    return { ok: true, code: '' }
  }

  let parsed
  try {
    parsed = JSON.parse(jsonString)
  } catch (e) {
    return { ok: false, error: 'JSON 解析失败：' + e.message }
  }

  const trimmedName = (typeName || '').trim()
  const isValidName = trimmedName === '' || RS_IDENT_RE.test(trimmedName)
  const safeName = isValidName ? (trimmedName || 'AutoGenerated') : 'AutoGenerated'
  const warning = isValidName
    ? undefined
    : `结构体名 "${trimmedName}" 不是合法 Rust 标识符`

  try {
    const jsonInput = jsonInputForTargetLanguage('rust')
    await jsonInput.addSource({ name: safeName, samples: [JSON.stringify(parsed)] })
    const inputData = new InputData()
    inputData.addInput(jsonInput)

    const rendererOptions = {
      'leading-comments': false,
      'derive-debug': deriveDebug,
      'derive-clone': deriveClone,
    }
    const extraOptions = {}
    if (skipNone) {
      rendererOptions['skip-serializing-none'] = true
      extraOptions.allPropertiesOptional = true
    }

    const result = await quicktype({
      lang: 'rust',
      inputData,
      rendererOptions,
      ...extraOptions,
    })
    return { ok: true, code: result.lines.join('\n'), warning }
  } catch (e) {
    return { ok: false, error: '生成失败：' + e.message }
  }
}
