export default [
  { path: '/', meta: { title: null, description: 'wxsm 的个人在线工具箱，包含编码转换、加密解密、文本处理等多种实用工具' } },
  { path: '/base64', meta: { title: 'Base64 转换', description: 'Base64 编码与解码' } },
  { path: '/gzip', meta: { title: 'Gzip 压缩', description: 'Gzip 压缩与解压（Base64 表示）' } },
  { path: '/diff', meta: { title: '文本对比', description: '文本对比，支持字符级差异与行内高亮' } },
  { path: '/watermark', meta: { title: '图片水印', description: '为图片添加透明文字水印' } },
  { path: '/aes-encrypt', meta: { title: '对称加密', description: 'AES 对称加密与解密' } },
  { path: '/hash-hmac', meta: { title: '哈希 / 散列', description: '哈希摘要与 HMAC 计算' } },
  { path: '/json', meta: { title: 'JSON 校验', description: 'JSON 校验、树形查看、格式化、压缩、Unicode 与转义转换' } },
  { path: '/file-base64', meta: { title: '文件转 Base64', description: '文件与 Base64 互转，支持图片预览' } },
  { path: '/rsa', meta: { title: 'RSA 加密', description: 'RSA 密钥生成、加密与解密' } },
  { path: '/url-encode', meta: { title: 'URL 编码', description: 'URL 编码与解码，支持批量处理' } },
  { path: '/case', meta: { title: '大小写转换', description: '大小写转换与编程命名风格转换' } },
  { path: '/timestamp', meta: { title: '时间戳转换', description: 'Unix 时间戳 ↔ 日期时间转换（10 位 / 13 位）' } },
  { path: '/md-html', meta: { title: 'Markdown 转换', description: 'Markdown ↔ HTML 双向转换', wide: true } },
  { path: '/qr-code', meta: { title: '二维码生成', description: '将文本或链接生成二维码，支持自定义颜色与纠错级别' } },
  { path: '/regex', meta: { title: '正则测试', description: '正则表达式实时测试与匹配高亮' } },
  { path: '/uuid', meta: { title: 'ID 生成', description: 'UUID v4 与 NanoID 生成' } },
  { path: '/html-entity', meta: { title: 'HTML 实体编码', description: 'HTML 特殊字符与实体互转' } },
  { path: '/password', meta: { title: '密码生成', description: '可配置长度、字符集的随机密码生成器' } },
  { path: '/color-picker', meta: { title: '取色器', description: '屏幕取色与 HEX / RGB / HSL 颜色互转' } },
  { path: '/ip-lookup', meta: { title: 'IP 查询', description: '查询 IP 地址归属地信息' } },
  { path: '/image-compress', meta: { title: '图片处理', description: '图片压缩、缩放与格式转换' } },
  { path: '/http-status', meta: { title: 'HTTP 状态码', description: 'HTTP 状态码含义速查' } },
  { path: '/unicode', meta: { title: 'Unicode 转换', description: 'Unicode 编码与解码' } },
  { path: '/url-parse', meta: { title: 'URL 解析', description: '拆分 URL 各部分与 Query 参数' } },
  { path: '/jwt-decode', meta: { title: 'JWT 解码', description: '解析 JWT Token 的 Header 与 Payload' } },
  { path: '/cron', meta: { title: 'Cron 解析', description: 'Cron 表达式解析与生成' } },
  { path: '/radix', meta: { title: '进制转换', description: '二进制 / 八进制 / 十进制 / 十六进制互转，支持 2-36 任意进制' } },
  { path: '/lorem', meta: { title: '占位文本', description: '中英文占位文本生成，可配置段落数与句数' } },
  { path: '/mime-types', meta: { title: 'MIME 类型', description: 'MIME 类型与文件扩展名速查' } },
  { path: '/box-shadow', meta: { title: '盒阴影', description: 'CSS box-shadow 可视化生成' } },
  { path: '/gradient', meta: { title: '渐变', description: 'CSS 渐变可视化生成' } },
  { path: '/border-radius', meta: { title: '圆角', description: 'CSS border-radius 可视化生成' } },
  { path: '/triangle', meta: { title: '三角形', description: 'CSS border 三角形生成' } },
]
