import {
  ArrowsRightLeftIcon,
  CircleStackIcon,
  CodeBracketSquareIcon,
  DocumentPlusIcon,
  SparklesIcon,
  LockClosedIcon,
  ShieldCheckIcon,
  PaperClipIcon,
  KeyIcon,
  LinkIcon,
  HashtagIcon,
  LanguageIcon,
  ClockIcon,
  DocumentTextIcon,
  QrCodeIcon,
  MagnifyingGlassIcon,
  FingerPrintIcon,
  EyeDropperIcon,
  CalendarDaysIcon,
  ChatBubbleBottomCenterTextIcon,
  CommandLineIcon,
  AdjustmentsHorizontalIcon,
  SignalIcon,
  GlobeAltIcon,
  PhotoIcon,
  TicketIcon,
  ServerIcon,
  CalculatorIcon,
  QueueListIcon,
  TagIcon,
  Square3Stack3DIcon,
  SwatchIcon,
  TableCellsIcon,
  Square2StackIcon,
  PlayIcon,
  FilmIcon,
  FaceSmileIcon,
  CameraIcon,
  CodeBracketIcon,
  CpuChipIcon,
  BeakerIcon,
  BoltIcon,
  ChartBarSquareIcon,
} from '@heroicons/vue/24/outline'

export const toolGroups = [
  {
    name: '编码转换',
    tools: [
      {
        name: 'Base64 转换',
        path: '/base64',
        desc: 'Base64 编码与解码',
        icon: ArrowsRightLeftIcon,
      },
      {
        name: 'URL 编码',
        path: '/url-encode',
        desc: 'URL 编码与解码，支持批量处理',
        icon: LinkIcon,
      },
      {
        name: 'HTML 实体编码',
        path: '/html-entity',
        desc: 'HTML 特殊字符与实体互转',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'Gzip 压缩',
        path: '/gzip',
        desc: 'Gzip 压缩与解压（Base64 表示）',
        icon: CircleStackIcon,
      },
      {
        name: 'Unicode 转换',
        path: '/unicode',
        desc: 'Unicode 编码与解码',
        icon: LanguageIcon,
      },
      {
        name: 'JWT 解码',
        path: '/jwt-decode',
        desc: '解析 JWT Token 的 Header 与 Payload',
        icon: TicketIcon,
      },
      {
        name: '进制转换',
        path: '/radix',
        desc: '二进制 / 八进制 / 十进制 / 十六进制互转，支持 2-36 任意进制',
        icon: CalculatorIcon,
      },
      {
        name: 'JSON → Go',
        path: '/json-to-go',
        desc: '将 JSON 样本转换为 Go 结构体定义',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → Go Map',
        path: '/json-to-go-map',
        desc: '将 JSON 转换为 Go map[string]interface{} 字面量',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → TypeScript',
        path: '/json-to-ts',
        desc: '将 JSON 样本转换为 TypeScript 类型定义，支持 interface / type 别名切换',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → Python',
        path: '/json-to-python',
        desc: '将 JSON 样本转换为 Python 类型定义，支持 pydantic BaseModel',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → Rust',
        path: '/json-to-rust',
        desc: '将 JSON 样本转换为 Rust struct 定义，支持 derive 与 skip_serializing_none',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → Java',
        path: '/json-to-java',
        desc: '将 JSON 样本转换为 Java POJO，支持 List<T> 与 Lombok',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → C++',
        path: '/json-to-cpp',
        desc: '将 JSON 样本转换为 C++ struct，支持自定义命名空间',
        icon: CodeBracketSquareIcon,
      },
      {
        name: 'JSON → C#',
        path: '/json-to-csharp',
        desc: '将 JSON 样本转换为 C# 类型定义，支持 List<T> 与自定义命名空间',
        icon: CodeBracketSquareIcon,
      },
    ],
  },
  {
    name: '加解密',
    tools: [
      {
        name: '对称加密',
        path: '/aes-encrypt',
        desc: 'AES 对称加密与解密',
        icon: LockClosedIcon,
      },
      {
        name: '哈希 / 散列',
        path: '/hash-hmac',
        desc: '哈希摘要与 HMAC 计算',
        icon: ShieldCheckIcon,
      },
      {
        name: 'RSA 加密',
        path: '/rsa',
        desc: 'RSA 密钥生成、加密与解密',
        icon: KeyIcon,
      },
    ],
  },
  {
    name: '生成转换',
    tools: [
      {
        name: '密码生成',
        path: '/password',
        desc: '可配置长度、字符集的随机密码生成器',
        icon: HashtagIcon,
      },
      {
        name: 'ID 生成',
        path: '/uuid',
        desc: 'UUID v4 与 NanoID 生成',
        icon: FingerPrintIcon,
      },
      {
        name: '时间戳转换',
        path: '/timestamp',
        desc: 'Unix 时间戳 ↔ 日期时间转换（10 位 / 13 位）',
        icon: ClockIcon,
      },
      {
        name: '取色器',
        path: '/color-picker',
        desc: '屏幕取色与 HEX / RGB / HSL 颜色互转',
        icon: EyeDropperIcon,
      },
      {
        name: 'Markdown 转换',
        path: '/md-html',
        desc: 'Markdown ↔ HTML 双向转换',
        icon: DocumentTextIcon,
      },
      {
        name: 'SVG 预览',
        path: '/svg-preview',
        desc: 'SVG 代码实时预览，支持美化 / 压缩、Data URI、颜色覆盖与下载',
        icon: BeakerIcon,
      },
      {
        name: 'Cron 解析',
        path: '/cron',
        desc: 'Cron 表达式解析与生成',
        icon: CalendarDaysIcon,
      },
      {
        name: '占位文本',
        path: '/lorem',
        desc: '中英文占位文本生成，可配置段落数与句数',
        icon: QueueListIcon,
      },
    ],
  },
  {
    name: 'CSS',
    tools: [
      {
        name: '盒阴影',
        path: '/box-shadow',
        desc: 'CSS box-shadow 可视化生成',
        icon: Square3Stack3DIcon,
      },
      {
        name: '渐变',
        path: '/gradient',
        desc: 'CSS 渐变可视化生成',
        icon: SwatchIcon,
      },
      {
        name: '圆角',
        path: '/border-radius',
        desc: 'CSS border-radius 可视化生成',
        icon: Square2StackIcon,
      },
      {
        name: '三角形',
        path: '/triangle',
        desc: 'CSS border 三角形生成',
        icon: PlayIcon,
      },
      {
        name: '动画',
        path: '/css-animation',
        desc: 'CSS animation 可视化生成',
        icon: FilmIcon,
      },
      {
        name: '贝塞尔曲线',
        path: '/cubic-bezier',
        desc: 'CSS cubic-bezier 缓动曲线可视化编辑，可拖拽控制点、预览动画',
        icon: ChartBarSquareIcon,
      },
    ],
  },
  {
    name: '文本处理',
    tools: [
      {
        name: '文本对比',
        path: '/diff',
        desc: '文本对比，支持字符级差异与行内高亮',
        icon: DocumentPlusIcon,
      },
      {
        name: 'JSON 校验',
        path: '/json',
        desc: 'JSON 校验、树形查看、格式化、压缩、Unicode 与转义转换',
        icon: CommandLineIcon,
      },
      {
        name: '正则测试',
        path: '/regex',
        desc: '正则表达式实时测试与匹配高亮',
        icon: MagnifyingGlassIcon,
      },
      {
        name: '大小写转换',
        path: '/case',
        desc: '大小写转换与编程命名风格转换',
        icon: AdjustmentsHorizontalIcon,
      },
      {
        name: 'Patch 查看',
        path: '/patch-viewer',
        desc: '可视化查看 git diff / unified patch 文件',
        icon: CodeBracketIcon,
      },
      {
        name: '命令行格式转换',
        path: '/cli-format',
        desc: '命令行参数单行与多行风格互转,支持 Unix shell 引号与转义',
        icon: CommandLineIcon,
      },
      {
        name: 'CSV 预览',
        path: '/csv',
        desc: 'CSV 表格预览，支持类型推断、列统计、排序筛选、导出',
        icon: TableCellsIcon,
      },
      {
        name: 'Emoji 大全',
        path: '/emoji',
        desc: 'Emoji 查询与多种格式复制',
        icon: FaceSmileIcon,
      },
    ],
  },
  {
    name: '图片',
    tools: [
      {
        name: '图片水印',
        path: '/watermark',
        desc: '为图片添加透明文字水印',
        icon: SparklesIcon,
      },
      {
        name: '文件转 Base64',
        path: '/file-base64',
        desc: '文件与 Base64 互转，支持图片预览',
        icon: PaperClipIcon,
      },
      {
        name: '二维码生成',
        path: '/qr-code',
        desc: '将文本或链接生成二维码，支持自定义颜色与纠错级别',
        icon: QrCodeIcon,
      },
      {
        name: '图片处理',
        path: '/image-compress',
        desc: '图片压缩、缩放与格式转换',
        icon: PhotoIcon,
      },
      {
        name: '代码截图',
        path: '/code-screenshot',
        desc: '代码语法高亮截图，支持多语言与主题',
        icon: CameraIcon,
      },
    ],
  },
  {
    name: '网络',
    tools: [
      {
        name: 'IP 查询',
        path: '/ip-lookup',
        desc: '查询 IP 地址归属地信息',
        icon: GlobeAltIcon,
      },
      {
        name: 'URL 解析',
        path: '/url-parse',
        desc: '拆分 URL 各部分与 Query 参数',
        icon: ServerIcon,
      },
      {
        name: 'HTTP 状态码',
        path: '/http-status',
        desc: 'HTTP 状态码含义速查',
        icon: SignalIcon,
      },
      {
        name: 'MIME 类型',
        path: '/mime-types',
        desc: 'MIME 类型与文件扩展名速查',
        icon: TagIcon,
      },
    ],
  },
  {
    name: 'LLM',
    tools: [
      {
        name: 'Token 计数器',
        path: '/token-counter',
        desc: '估算 LLM 提示词 token 数，支持纯文本与 messages 模式，可视化分词',
        icon: ChatBubbleBottomCenterTextIcon,
      },
      {
        name: 'KV Cache 计算器',
        path: '/kv-cache',
        desc: '估算 LLM KV Cache 显存占用,或根据 GPU 显存反推最大可缓存 token 数',
        icon: CpuChipIcon,
      },
    ],
  },
  {
    name: '硬件',
    tools: [
      {
        name: '键盘测试',
        path: '/keyboard-tester',
        desc: '在线键盘按键检测，支持 ANSI 104 全键盘与 87 TKL 布局切换',
        icon: BoltIcon,
      },
    ],
  },
]
